// module.exports = {
//   content: ["./src/**/*.vue", "./public/**/*.html"],
//   theme: {
//     extend: {
//       colors: {
//         brand: "red",
//         primaryblack: "#333 !important",
//         primarygray: "#000000bd !important",
//         darkBlue: "#0F3D7A !important",
//         lightGray: "#4F4F4F !important",
//         BrandColor: "var(--primary-color-brand) !important",
//         "page-background": "var(--page-background)",
//         "container-background": "var(--container-background)",
//         "page-border": "var(--page-border)",
//         "primary-color-brand": "var(--primary-color-brand)",
//         "brand-500": "var(--brand-500)",
//         "brand-400": "var(--brand-400)",
//         "brand-300": "var(--brand-300)",
//         "brand-200": "var(--brand-200)",
//         "brand-100": "var(--brand-100)",
//         "brand-50": "var(--brand-50)",
//         "black-950": "var(--black-950)",
//         "black-900": "var(--black-900)",
//         "black-800": "var(--black-800)",
//         "black-700": "var(--black-700)",
//         "black-600": "var(--black-500)",
//         "black-500": "var(--black-500)",
//         "black-400": "var(--black-400)",
//         "black-300": "var(--black-300) !important",
//         "black-200": "var(--black-200)",
//         "black-150": "var(--black-150)",
//         "black-100": "var(--black-100)",
//         "black-50": "var(--black-50)",
//         "card-color": "var(--card-color)",
//         "card-border": "var(--card-border)",
//         "filter-border": "var(--filter-border)",
//         "color-black": "var(--color-black)",
//         "color-white": "var(--color-white)",
//         "hyper-links-blue": "var(--hyper-links-blue)",
//         "active-color": "var(--active-color)",
//         "inactive-color": "var(--inactive-color)",
//         "green-assign-color": "var(--green-assign-color)",
//         "note-orenge-color": "var(--note-orenge-color)",
//         "text-gray-color": "var(--text-gray-color)",
//         tailwind: "#0F3D7A",
//       },
//       filter: {
//         "blur-custom": "blur(100px)",
//       },
//       fontFamily: {
//         poppin: ["Poppins", "sans-serif"],
//       },
//       screen: {
//         "3xl": "1920px",
//       },
//       fontSize: {
//         xxs: "10px !important",
//         smd: "13px !important",
//         mds: "15px !important",
//       },
//       boxShadow: {
//         custom: " 0px 0px 12px 0px rgba(0, 0, 0, 0.06) !important",
//       },
//       height: {
//         dashboardHeight: "calc(100vh - 230px) !important",
//         tableScreenHeight: "calc(100vh - 280px) !important",
//         mainCardHeight: "calc(100vh - 80px) !important",
//         viewCardHeight: "calc(100vh - 165px) !important",
//       },
//     },
//   },
//   plugins: [],
// };
